# Usage: ansible-playbook -e TAG1=a -e TAG2=b -e TAG3=c docker-image_pull.yaml

---
- name: Pull Docker Images
  hosts: all
  vars:
    REG_URL: "harbor.example.com"
    REG_USER: "user"
    REG_TOKEN: "password"
    TAG1: ""
    TAG2: ""
    TAG3: ""
  tasks:
    - name: Log Into Docker Registry
      docker_login:
        registry_url: "{{ REG_URL }}"
        username: "{{ REG_USER }}"
        password: "{{ REG_TOKEN }}"

    - name: Pull Image A
      docker_image:
        name: "{{ REG_URL }}/library/A"
        tag: "{{ TAG1 }}"
        source: pull
        force_source: yes
        state: present
      when: TAG1 != ""

    - name: Pull Image B
      docker_image:
        name: "{{ REG_URL }}/library/B"
        tag: "{{ TAG2 }}"
        source: pull
        force_source: yes
        state: present
      when: TAG2 != ""

    - name: Pull Image C
      docker_image:
        name: "{{ REG_URL }}/library/C"
        tag: "{{ TAG3 }}"
        source: pull
        force_source: yes
        state: present
      when: TAG3 != ""

    - name: Prune Docker Dangling Images
      docker_prune:
        images: yes
        images_filters:
          dangling: yes
